name: modflow6

channels:
  - conda-forge
  - defaults

dependencies:
  - appdirs
  - filelock
  - flaky
  - fortls
  - fprettify
  - jupytext
  - matplotlib
  - meson>=1.1.0
  - ninja
  - numpy
  - pip
  - pip:
      - git+https://github.com/modflowpy/flopy.git
      - git+https://github.com/modflowpy/pymake.git
      - git+https://github.com/Deltares/xmipy.git
      - git+https://github.com/MODFLOW-USGS/modflowapi.git
      - modflow-devtools
  - pytest
  - pytest-cases
  - pytest-dotenv
  - pytest-order
  - pytest-xdist
  
