name: modflow6

channels:
  - conda-forge
  - defaults

dependencies:
  - appdirs
  - filelock
  - fprettify
  - jupytext
  - matplotlib
  - meson>=1.1.0
  - ninja
  - numpy
  - pip
  - pip:
      - https://github.com/w-bonelli/flopy/archive/prt-utils.zip
      - git+https://github.com/modflowpy/pymake.git
      - git+https://github.com/Deltares/xmipy.git
      - git+https://github.com/MODFLOW-USGS/modflowapi.git
      - modflow-devtools
      - flopy[test,optional]
      - fortls
  - pytest
  - pytest-cases
  - pytest-dotenv
  - pytest-order
  - pytest-xdist
  - flaky