name: 'Setup usgslatex'
description: 'Install USGS LaTeX style files and Univers font'
runs:
  steps:
    # steps below run only on Linux to test distribution procedures, e.g.
    # compiling binaries, building documentation
    - name: Checkout usgslatex
      if: runner.os == 'Linux'
      uses: actions/checkout@v3
      with:
        repository: MODFLOW-USGS/usgslatex
        path: usgslatex

    - name: Install TeX Live
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt install texlive-science \
          texlive-latex-extra \
          texlive-font-utils \
          texlive-fonts-recommended \
          texlive-fonts-extra

    - name: Install USGS LaTeX style files and Univers font
      if: runner.os == 'Linux'
      working-directory: usgslatex/usgsLaTeX
      run: sudo ./install.sh --all-users