name: Test parallel MF6 (Windows)
description: Build and test parallel MODFLOW 6 on Windows
runs:
  using: "composite"
  steps:

    - name: Build MF6 parallel
      uses: ./modflow6/.github/actions/build-par-win

    - name: Update flopy
      working-directory: modflow6/autotest
      shell: cmd
      run: micromamba run -r "C:\Users\runneradmin\micromamba" -n modflow6 python update_flopy.py

    - name: Get executables
      working-directory: modflow6/autotest
      shell: cmd
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: micromamba run -r "C:\Users\runneradmin\micromamba" -n modflow6 pytest -v --durations 0 get_exes.py

    - name: Test programs
      working-directory: modflow6/autotest
      shell: cmd 
      env:
        REPOS_PATH: ${{ github.workspace }}
      run: |
        "%ONEAPI_ROOT%\setvars.bat" intel64 vs2022 && "%TEMP%\test_modflow6.bat