name: MODFLOW 6 post-release reset
on:
  release:
    types:
      - published
env:
  FC: ifort
jobs:
  reset:
    name: Open reset PR
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          path: modflow6

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: modflow6/environment.yml
          cache-downloads: true
          cache-env: true

      - name: Get release tag
        uses: oprypin/find-latest-tag@v1
        id: latest_tag
        with:
          repository: MODFLOW-USGS/modflow6
          releases-only: true

      - name: Create pull request
        working-directory: modflow6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # create reset branch from master
          reset_branch="post-release-${{ steps.latest_tag.outputs.tag }}-reset"
          git fetch origin
          git checkout master
          git switch -c $reset_branch
          
          # increment minor version from latest official release and reset IDEVELOPMODE to 1
          major_version=$(echo "${{ steps.latest_tag.outputs.tag }}" | cut -d. -f1)
          minor_version=$(echo "${{ steps.latest_tag.outputs.tag }}" | cut -d. -f2)
          version="$major_version.$((minor_version + 1)).0"
          python distribution/update_version.py -v "$version"
          
          # commit and push to reset branch
          git config core.sharedRepository true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "ci(release): reinitialize develop for next release"
          git push -u origin $reset_branch
          
          # create PR into develop
          body='
          # Reinitialize for development
          
          Updates the `develop` branch from `master` following an approved release. Bumps the minor version number, resets version files, and sets `IDEVELOPMODE` back to `1`.
          '
          gh pr create -B "develop" -H "$reset_branch" --title "Reinitialize develop to $version" --draft --body "$body"